import { Profissional, Aluno, AvaliacaoFisica, DesafioTemplate, RadarAlerta, WhatsAppMensagem, FotoEvolucao, DesafioEnviado, Lead, LeadInteracao } from '../types';
import { DESAFIOS_LEADS_CONVERSAO } from './leadsFollowupUtils';
import { DESAFIOS_NATIVOS_RADARMOVE } from './seeds/desafiosSeed';

export const mockProfissional: Profissional = {
  id: 'prof-001',
  nome_empresa: 'RadarMove Personal Studio',
  nome_profissional: 'Treinador Rodrigo Silva',
  telefone: '5511987654321',
  cor_primaria: '#10b981',
  total_alunos: 24,
};

export const mockAlunos: Aluno[] = [
  {
    id: 'aluno-01',
    profissional_id: 'prof-001',
    nome: 'João Pedro Ramos',
    telefone: '5511991234567',
    data_nascimento: '1992-05-14',
    status: 'em_risco',
    ultimo_checkin: '2026-09-11T08:30:00Z',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    objetivo: 'Hipertrofia e melhora postural',
    dias_sem_treino: 6,
    plano: 'Presencial VIP 3x/semana',
    frequencia_semanal: 3,
    altura_cm: 180,
  },
  {
    id: 'aluno-02',
    profissional_id: 'prof-001',
    nome: 'Ana Clara Albuquerque',
    telefone: '5511982345678',
    data_nascimento: '1995-09-18', // Aniversário amanhã!
    status: 'ativo',
    ultimo_checkin: '2026-09-16T18:45:00Z',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    objetivo: 'Emagrecimento e redução de gordura visceral',
    dias_sem_treino: 1,
    plano: 'Consultoria Híbrida 4x/semana',
    frequencia_semanal: 4,
    altura_cm: 165,
  },
  {
    id: 'aluno-03',
    profissional_id: 'prof-001',
    nome: 'Lucas Mendes Ferraz',
    telefone: '5511973456789',
    data_nascimento: '1988-11-20',
    status: 'em_risco',
    ultimo_checkin: '2026-09-12T07:15:00Z',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    objetivo: 'Condicionamento físico e longevidade',
    dias_sem_treino: 5,
    plano: 'Presencial 2x/semana',
    frequencia_semanal: 2,
    altura_cm: 176,
  },
  {
    id: 'aluno-04',
    profissional_id: 'prof-001',
    nome: 'Camila Rocha Nogueira',
    telefone: '5511964567890',
    data_nascimento: '1998-03-09',
    status: 'ativo',
    ultimo_checkin: '2026-09-17T06:40:00Z',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    objetivo: 'Ganho de massa magra e definição',
    dias_sem_treino: 0,
    plano: 'Presencial VIP 3x/semana',
    frequencia_semanal: 3,
    altura_cm: 168,
  },
  {
    id: 'aluno-05',
    profissional_id: 'prof-001',
    nome: 'Bruno Carvalho Siqueira',
    telefone: '5511955678901',
    data_nascimento: '1985-07-22',
    status: 'inativo',
    ultimo_checkin: '2026-08-25T19:00:00Z',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    objetivo: 'Reabilitação lombar e fortalecimento',
    dias_sem_treino: 23,
    plano: 'Consultoria Online',
    frequencia_semanal: 2,
    altura_cm: 182,
  },
];

export const mockAvaliacoes: AvaliacaoFisica[] = [
  {
    id: 'av-01-1',
    aluno_id: 'aluno-01',
    data_registro: '2026-06-15',
    circ_abdominal: 94.5,
    perc_gordura: 24.2,
    massa_muscular: 33.1,
    gordura_visceral: 8,
    taxa_metabolica: 1680,
    peso: 84.5,
    altura_cm: 180,
    observacoes: 'Início do plano de ganho muscular e correção de sobrecarga lombar.',
  },
  {
    id: 'av-01-2',
    aluno_id: 'aluno-01',
    data_registro: '2026-07-20',
    circ_abdominal: 92.0,
    perc_gordura: 22.8,
    massa_muscular: 34.0,
    gordura_visceral: 7.5,
    taxa_metabolica: 1710,
    peso: 83.8,
    altura_cm: 180,
    observacoes: 'Boa adesão proteica. Redução visível na circunferência abdominal.',
  },
  {
    id: 'av-01-3',
    aluno_id: 'aluno-01',
    data_registro: '2026-08-22',
    circ_abdominal: 89.5,
    perc_gordura: 21.0,
    massa_muscular: 35.2,
    gordura_visceral: 7,
    taxa_metabolica: 1745,
    peso: 82.9,
    altura_cm: 180,
    observacoes: 'Evolução consistente na bioimpedância. Massa muscular subiu 1.2kg.',
  },
  {
    id: 'av-01-4',
    aluno_id: 'aluno-01',
    data_registro: '2026-09-15',
    circ_abdominal: 87.8,
    perc_gordura: 19.8,
    massa_muscular: 36.1,
    gordura_visceral: 6,
    taxa_metabolica: 1770,
    peso: 82.1,
    altura_cm: 180,
    observacoes: 'Melhor resultado até agora! Massa magra em alta e abdômen recuando.',
  },
  // Avaliações de Ana Clara
  {
    id: 'av-02-1',
    aluno_id: 'aluno-02',
    data_registro: '2026-07-01',
    circ_abdominal: 82.0,
    perc_gordura: 29.5,
    massa_muscular: 23.4,
    gordura_visceral: 6,
    taxa_metabolica: 1390,
    peso: 65.0,
    altura_cm: 165,
  },
  {
    id: 'av-02-2',
    aluno_id: 'aluno-02',
    data_registro: '2026-08-15',
    circ_abdominal: 78.5,
    perc_gordura: 26.8,
    massa_muscular: 24.6,
    gordura_visceral: 5,
    taxa_metabolica: 1430,
    peso: 63.2,
    altura_cm: 165,
  },
  {
    id: 'av-02-3',
    aluno_id: 'aluno-02',
    data_registro: '2026-09-10',
    circ_abdominal: 75.2,
    perc_gordura: 24.5,
    massa_muscular: 25.4,
    gordura_visceral: 4,
    taxa_metabolica: 1460,
    peso: 61.8,
    altura_cm: 165,
    observacoes: 'Excelente avanço. Redução de 6.8cm na circunferência abdominal.',
  },
  // Avaliações de Lucas Mendes (aluno-03 - em risco)
  {
    id: 'av-03-1',
    aluno_id: 'aluno-03',
    data_registro: '2026-07-10',
    circ_abdominal: 98.0,
    perc_gordura: 26.5,
    massa_muscular: 31.0,
    gordura_visceral: 9,
    taxa_metabolica: 1620,
    peso: 88.0,
    observacoes: 'Avaliação inicial. Foco em disciplina alimentar e constância nos treinos.',
  },
  {
    id: 'av-03-2',
    aluno_id: 'aluno-03',
    data_registro: '2026-08-18',
    circ_abdominal: 95.5,
    perc_gordura: 25.0,
    massa_muscular: 31.8,
    gordura_visceral: 8,
    taxa_metabolica: 1650,
    peso: 86.5,
    observacoes: 'Houve melhora, porém as viagens frequentes interromperam a rotina.',
  },
  // Avaliações de Mariana Costa (aluno-04)
  {
    id: 'av-04-1',
    aluno_id: 'aluno-04',
    data_registro: '2026-06-01',
    circ_abdominal: 79.0,
    perc_gordura: 27.0,
    massa_muscular: 22.0,
    gordura_visceral: 5,
    taxa_metabolica: 1350,
    peso: 59.0,
    observacoes: 'Avaliação inicial para meia-maratona.',
  },
  {
    id: 'av-04-2',
    aluno_id: 'aluno-04',
    data_registro: '2026-07-15',
    circ_abdominal: 76.5,
    perc_gordura: 24.8,
    massa_muscular: 23.1,
    gordura_visceral: 4,
    taxa_metabolica: 1390,
    peso: 58.2,
    observacoes: 'Fortalecimento de core e glúteo surtindo efeito.',
  },
  {
    id: 'av-04-3',
    aluno_id: 'aluno-04',
    data_registro: '2026-08-30',
    circ_abdominal: 74.0,
    perc_gordura: 22.5,
    massa_muscular: 24.2,
    gordura_visceral: 3,
    taxa_metabolica: 1420,
    peso: 57.5,
    observacoes: 'Bateu recorde pessoal de 10km! Ótima densidade muscular.',
  },
  // Avaliações de Bruno Carvalho (aluno-05 - inativo)
  {
    id: 'av-05-1',
    aluno_id: 'aluno-05',
    data_registro: '2026-06-20',
    circ_abdominal: 102.0,
    perc_gordura: 28.0,
    massa_muscular: 34.0,
    gordura_visceral: 10,
    taxa_metabolica: 1720,
    peso: 93.0,
    observacoes: 'Quadro de dor lombar crônica e sedentarismo.',
  },
  {
    id: 'av-05-2',
    aluno_id: 'aluno-05',
    data_registro: '2026-08-01',
    circ_abdominal: 99.0,
    perc_gordura: 26.5,
    massa_muscular: 34.8,
    gordura_visceral: 9,
    taxa_metabolica: 1750,
    peso: 91.2,
    observacoes: 'Alívio nas dores articulares com exercícios de mobilidade.',
  },
];

export const mockDesafiosTemplates: DesafioTemplate[] = [
  // Categoria: Lifestyle 23h
  {
    id: 'des-01',
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Regra dos 500ml ao Acordar',
    mensagem_whatsapp: 'Fala {aluno}! Passando pra te lembrar da nossa regra das 23h: 500ml de água antes de qualquer café ou tela logo ao levantar. Já bateu esse micro-hábito hoje? Me manda um 💧 quando fizer!',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-02',
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Caminhada Pós-Almoço 10 min',
    mensagem_whatsapp: 'E aí {aluno}! Desafio Lifestyle 23h de hoje: 10 minutinhos de caminhada leve logo após o almoço para controlar o pico de insulina e digestão. Topa esse combinado comigo hoje? 🚶‍♂️💨',
    tempo_estimado: '10 min',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-03',
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Higiene do Sono & Luz Azul',
    mensagem_whatsapp: 'Opa {aluno}! Seu resultado de hipertrofia é construído no sono. Desafio de hoje: desligar telas ou ativar filtro amarelo 40 min antes de dormir. Amanhã me conta se acordou mais disposto! 🌙',
    tempo_estimado: '40 min',
    dificuldade: 'Médio',
  },

  // Categoria: Desafio de Bolso
  {
    id: 'des-04',
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Micro-Pausa Postural: 30s Prancha',
    mensagem_whatsapp: 'Opa {aluno}! Desafio de bolso agora: levanta da cadeira, 30 segundinhos de prancha isométrica ou 20 agachamentos livres para destravar o quadril e lombar. Fez? Me manda um check ✅!',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-05',
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Meta Relâmpago de Proteína',
    mensagem_whatsapp: 'Fala {aluno}! Como foi o almoço? Lembra da nossa meta de bater proteína limpa hoje. Me manda uma foto do prato ou do shake pra eu avaliar rapidinho!',
    tempo_estimado: '2 min',
    dificuldade: 'Médio',
  },
  {
    id: 'des-06',
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Meta 3 Litros de Água',
    mensagem_whatsapp: 'Fala {aluno}! Como tá a garrafa do lado da mesa? A meta de hoje é bater 3L antes das 18h. Se já estiver na metade, me responde com a foto da garrafa! 💧💪',
    tempo_estimado: 'Imediato',
    dificuldade: 'Fácil',
  },

  // Categoria: Estoicismo
  {
    id: 'des-07',
    profissional_id: null,
    categoria: 'Estoicismo',
    titulo: 'Vitória sobre a Resistência',
    mensagem_whatsapp: 'Bom dia {aluno}! “Não controlamos o cansaço do dia, mas controlamos a honra de cumprir o combinado”. Nosso treino de hoje já está agendado. Te espero focado e pronto pra vencer a resistência!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Médio',
  },
  {
    id: 'des-08',
    profissional_id: null,
    categoria: 'Estoicismo',
    titulo: 'Foco no Processo, não no Imediatismo',
    mensagem_whatsapp: 'Fala {aluno}! Lembrete estoico: consistência supera intensidade esporádica. Mesmo que o dia esteja corrido, 35 minutos bem executados valem mais que a perfeição adiada. Vamos pra cima!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-09',
    profissional_id: null,
    categoria: 'Estoicismo',
    titulo: 'Mente Firme em Dias Difíceis',
    mensagem_whatsapp: 'E aí {aluno}! Os dias em que você menos quer treinar são exatamente os que mais transformam sua disciplina. Vence a mente e bota o tênis. Tô te esperando na sala!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Desafiador',
  },

  // Categoria: Nutrição
  {
    id: 'des-10',
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Meta Proteína na Primeira Refeição',
    mensagem_whatsapp: 'Fala {aluno}! Desafio nutricional de hoje: garantir pelo menos 25g a 30g de proteína de qualidade no seu café da manhã ou primeira refeição. Isso reduz a fome noturna e segura o foco. Me conta o que mandou pra dentro!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-11',
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Zero Açúcar Líquido por 24h',
    mensagem_whatsapp: 'Opa {aluno}! Desafio de 24h: substituir refrigerantes e sucos industrializados por água mineral, chá gelado ou café puro. Topa esse teste de disciplina hoje? Vamos juntos!',
    tempo_estimado: '24h',
    dificuldade: 'Médio',
  },

  // Categoria: Recuperação
  {
    id: 'des-12',
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Alongamento Noturno de Quadril & Lombar',
    mensagem_whatsapp: 'E aí {aluno}! Antes de deitar hoje: 5 minutinhos de respiração profunda e alívio do psoas/lombar (posição da criança + borboleta). Ajuda a relaxar o sistema nervoso e melhorar o sono. Fez? Me dá um toque!',
    tempo_estimado: '5 min',
    dificuldade: 'Fácil',
  },
  {
    id: 'des-13',
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Banho Morno & Desconexão Digital',
    mensagem_whatsapp: 'Fala {aluno}! Desafio de recuperação para recarregar o sistema: banho morno para relaxar a musculatura e celular no modo não perturbe 30 min antes de dormir. Bora recuperar pro próximo treino!',
    tempo_estimado: '15 min',
    dificuldade: 'Fácil',
  },
  ...DESAFIOS_NATIVOS_RADARMOVE.map((des, index) => ({
    ...des,
    id: `des-nativo-${String(index + 1).padStart(2, '0')}`,
  })),
  ...DESAFIOS_LEADS_CONVERSAO,
];

export const mockAlertasRadar: RadarAlerta[] = [
  {
    id: 'alert-01',
    aluno_id: 'aluno-01',
    aluno_nome: 'João Pedro Ramos',
    aluno_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    aluno_telefone: '5511991234567',
    tipo: 'cancelamento',
    descricao: 'Cancelou o treino de hoje às 07:00 com justificativa de reunião de trabalho.',
    tempo_atras: 'Há 45 minutos',
    urgencia: 'alta',
    desafio_sugerido_id: 'des-04', // Micro-pausa postural ou desafio de bolso
  },
  {
    id: 'alert-02',
    aluno_id: 'aluno-02',
    aluno_nome: 'Ana Clara Albuquerque',
    aluno_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    aluno_telefone: '5511982345678',
    tipo: 'aniversario',
    descricao: 'Faz aniversário amanhã (18/09)! Momento de ouro para fidelização e carinho.',
    tempo_atras: 'Amanhã',
    urgencia: 'media',
    desafio_sugerido_id: 'des-01',
  },
  {
    id: 'alert-03',
    aluno_id: 'aluno-03',
    aluno_nome: 'Lucas Mendes Ferraz',
    aluno_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    aluno_telefone: '5511973456789',
    tipo: 'sem_treino',
    descricao: 'Sem check-in há 5 dias. Risco iminente de desengajamento e cancelamento de plano.',
    tempo_atras: '5 dias sem check-in',
    urgencia: 'alta',
    desafio_sugerido_id: 'des-07', // Estoicismo - Vencer a resistência
  },
  {
    id: 'alert-04',
    aluno_id: 'aluno-04',
    aluno_nome: 'Camila Rocha Nogueira',
    aluno_avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    aluno_telefone: '5511964567890',
    tipo: 'meta_batida',
    descricao: 'Bateu 12 treinos seguidos no mês! Ótimo momento para enviar reforço positivo.',
    tempo_atras: 'Hoje às 06:40',
    urgencia: 'baixa',
    desafio_sugerido_id: 'des-08',
  },
];

export const mockWhatsAppFeed: WhatsAppMensagem[] = [
  {
    id: 'wpp-01',
    aluno_id: 'aluno-01',
    aluno_nome: 'João Pedro',
    texto: 'Rodrigo, consegui fazer a prancha de 30s aqui no intervalo do trampo! Valeu pelo puxão de orelha kkk',
    data_hora: '10:42',
    origem: 'aluno',
    lida: false,
  },
  {
    id: 'wpp-02',
    aluno_id: 'aluno-04',
    aluno_nome: 'Camila Rocha',
    texto: 'Treino de perna hoje foi destruidor haha! Perna bamba até agora 💪🔥',
    data_hora: '09:15',
    origem: 'aluno',
    lida: true,
  },
  {
    id: 'wpp-03',
    aluno_id: 'aluno-02',
    aluno_nome: 'Ana Clara',
    texto: 'Já tomei os 500ml com limão logo ao acordar! Meta do Lifestyle 23h cumprida!',
    data_hora: '07:30',
    origem: 'aluno',
    lida: true,
  },
  {
    id: 'wpp-04',
    aluno_id: 'aluno-03',
    aluno_nome: 'Lucas Mendes',
    texto: 'Cara, tava desanimado hoje, mas li a mensagem sobre resistência e vou aí no treino das 19h!',
    data_hora: 'Ontem 18:22',
    origem: 'aluno',
    lida: true,
  },
];

export const mockFotosEvolucao: FotoEvolucao[] = [
  // Fotos de João Pedro Ramos (aluno-01)
  {
    id: 'foto-01-antes-frente',
    aluno_id: 'aluno-01',
    data: '2026-06-15',
    foto_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&auto=format&fit=crop&q=80',
    angulo: 'frente',
    peso_kg: 84.5,
    etiqueta: 'Início da Consultoria',
    observacoes: 'Postura inicial com leve anteriorização de ombros e retenção hídrica abdominal.',
  },
  {
    id: 'foto-01-depois-frente',
    aluno_id: 'aluno-01',
    data: '2026-09-15',
    foto_url: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80',
    angulo: 'frente',
    peso_kg: 82.1,
    etiqueta: 'Atual (90 Dias)',
    observacoes: 'Grande melhora na densidade peitoral, alinhamento escapular e corte abdominal.',
  },
  {
    id: 'foto-01-antes-costas',
    aluno_id: 'aluno-01',
    data: '2026-06-15',
    foto_url: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=800&auto=format&fit=crop&q=80',
    angulo: 'costas',
    peso_kg: 84.5,
    etiqueta: 'Início da Consultoria',
    observacoes: 'Dorsal com pouca ativação e menor tônus romboide.',
  },
  {
    id: 'foto-01-depois-costas',
    aluno_id: 'aluno-01',
    data: '2026-09-15',
    foto_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    angulo: 'costas',
    peso_kg: 82.1,
    etiqueta: 'Atual (90 Dias)',
    observacoes: 'Expansão dorsal evidente e redução das dobras nas costas.',
  },

  // Fotos de Ana Clara Albuquerque (aluno-02)
  {
    id: 'foto-02-antes',
    aluno_id: 'aluno-02',
    data: '2026-07-01',
    foto_url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80',
    angulo: 'frente',
    peso_kg: 65.0,
    etiqueta: 'Início',
    observacoes: 'Foco inicial em reeducação metabólica e força base.',
  },
  {
    id: 'foto-02-meio',
    aluno_id: 'aluno-02',
    data: '2026-08-15',
    foto_url: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&auto=format&fit=crop&q=80',
    angulo: 'perfil_direito',
    peso_kg: 63.2,
    etiqueta: '45 Dias',
    observacoes: 'Redução nítida de retenção e melhora do tônus de quadríceps.',
  },
  {
    id: 'foto-02-depois',
    aluno_id: 'aluno-02',
    data: '2026-09-10',
    foto_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format&fit=crop&q=80',
    angulo: 'frente',
    peso_kg: 61.8,
    etiqueta: 'Atual (70 Dias)',
    observacoes: 'Cintura afinou -6.8cm e definição muscular evidente!',
  },
];

export const mockDesafiosEnviados: DesafioEnviado[] = [
  {
    id: 'envio-01',
    aluno_id: 'aluno-01', // João Pedro
    aluno_nome: 'João Pedro Ramos',
    desafio_id: 'des-01',
    desafio_titulo: 'Regra dos 500ml ao Acordar',
    desafio_categoria: 'Lifestyle 23h',
    desafio_dificuldade: 'Fácil',
    mensagem_enviada: 'Fala João Pedro! Passando pra te lembrar da nossa regra das 23h: 500ml de água antes de qualquer café ou tela logo ao levantar. Já bateu esse micro-hábito hoje? Me manda um 💧 quando fizer!',
    data_envio: '2026-09-15T08:15:00Z',
    data_formatada: '15/09/2026 às 08:15',
    tempo_atras: 'Há 3 dias',
    vezes_enviado: 1,
    origem_disparo: 'individual',
  },
  {
    id: 'envio-02',
    aluno_id: 'aluno-01', // João Pedro
    aluno_nome: 'João Pedro Ramos',
    desafio_id: 'des-07',
    desafio_titulo: 'O Treino dos 15 Minutos',
    desafio_categoria: 'Estoicismo',
    desafio_dificuldade: 'Médio',
    mensagem_enviada: 'João Pedro, sem desculpas estoicas hoje: se o dia estiver caótico, combine comigo apenas 15 min de mobilidade e prancha. O treino imperfeito feito supera o treino perfeito nunca iniciado! 🛡️',
    data_envio: '2026-09-17T14:30:00Z',
    data_formatada: 'Ontem às 14:30',
    tempo_atras: 'Ontem',
    vezes_enviado: 1,
    origem_disparo: 'radar_alerta',
  },
  {
    id: 'envio-03',
    aluno_id: 'aluno-02', // Ana Clara
    aluno_nome: 'Ana Clara Albuquerque',
    desafio_id: 'des-02',
    desafio_titulo: 'Caminhada Pós-Almoço 10 min',
    desafio_categoria: 'Lifestyle 23h',
    desafio_dificuldade: 'Fácil',
    mensagem_enviada: 'E aí Ana Clara! Desafio Lifestyle 23h de hoje: 10 minutinhos de caminhada leve logo após o almoço para controlar o pico de insulina e digestão. Topa esse combinado comigo hoje? 🚶‍♂️💨',
    data_envio: '2026-09-16T12:45:00Z',
    data_formatada: '16/09/2026 às 12:45',
    tempo_atras: 'Há 2 dias',
    vezes_enviado: 1,
    origem_disparo: 'card_rapido',
  },
  {
    id: 'envio-04',
    aluno_id: 'aluno-03', // Lucas Mendes (em risco)
    aluno_nome: 'Lucas Mendes Ferraz',
    desafio_id: 'des-04',
    desafio_titulo: 'Micro-Pausa Postural: 30s Prancha',
    desafio_categoria: 'Desafio de Bolso',
    desafio_dificuldade: 'Fácil',
    mensagem_enviada: 'Opa Lucas! Desafio de bolso agora: levanta da cadeira, 30 segundinhos de prancha isométrica ou 20 agachamentos livres para destravar o quadril e lombar. Fez? Me manda um check ✅!',
    data_envio: '2026-09-14T11:00:00Z',
    data_formatada: '14/09/2026 às 11:00',
    tempo_atras: 'Há 4 dias',
    vezes_enviado: 1,
    origem_disparo: 'massa',
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-01',
    profissional_id: 'prof-001',
    nome: 'Mariana Vasconcelos',
    telefone: '5511984561234',
    email: 'mariana.vasconcelos@email.com',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    origem: 'instagram',
    objetivo_interesse: 'Emagrecimento pós-parto e tônus muscular',
    status: 'em_followup',
    temperatura: 'quente',
    desafio_ativo_id: 'des-lead-01',
    desafio_ativo_titulo: 'Desafio 3 Dias Sem Açúcar Líquido & Refri',
    data_envio_desafio: '2026-09-20T10:00:00Z',
    dias_desafio_decorridos: 1,
    etapa_followup: 2,
    data_criacao: '2026-09-18T14:20:00Z',
    ultimo_contato: '2026-09-20T10:00:00Z',
    proximo_followup: 'Hoje',
    valor_estimado_plano: 390,
    notas: 'Veio pelo Reels sobre emagrecimento sem passar fome. Muito motivada.',
    historico_interacoes: [
      {
        id: 'int-01',
        data: '2026-09-20T10:00:00Z',
        dataFormatada: 'Ontem às 10:00',
        tipo: 'desafio_enviado',
        titulo: 'Desafio Degustação Enviado',
        descricao: 'Enviado o Desafio 3 Dias Sem Açúcar Líquido pelo WhatsApp.',
      },
      {
        id: 'int-02',
        data: '2026-09-18T14:20:00Z',
        dataFormatada: '18/09/2026 às 14:20',
        tipo: 'mensagem_whatsapp',
        titulo: 'Primeiro Contato Direct Instagram',
        descricao: 'Perguntou como funciona a consultoria presencial e híbrida.',
      },
    ],
  },
  {
    id: 'lead-02',
    profissional_id: 'prof-001',
    nome: 'Renato Silveira',
    telefone: '5511976549876',
    email: 'renato.silveira@empresa.com.br',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    origem: 'indicacao',
    objetivo_interesse: 'Alívio de dores lombares e condicionamento para trabalho',
    status: 'desafio_enviado',
    temperatura: 'quente',
    desafio_ativo_id: 'des-lead-03',
    desafio_ativo_titulo: 'Desafio Detox Postural & Alívio de Lombar',
    data_envio_desafio: '2026-09-21T08:30:00Z',
    dias_desafio_decorridos: 0,
    etapa_followup: 1,
    data_criacao: '2026-09-21T08:15:00Z',
    ultimo_contato: '2026-09-21T08:30:00Z',
    proximo_followup: 'Amanhã',
    valor_estimado_plano: 450,
    notas: 'Indicado pelo aluno João Pedro. Trabalha 10h sentado como desenvolvedor.',
    historico_interacoes: [
      {
        id: 'int-03',
        data: '2026-09-21T08:30:00Z',
        dataFormatada: 'Hoje às 08:30',
        tipo: 'desafio_enviado',
        titulo: 'Desafio Postural Enviado',
        descricao: 'Enviou o Desafio de Alívio de Lombar de 3 minutos.',
      },
    ],
  },
  {
    id: 'lead-03',
    profissional_id: 'prof-001',
    nome: 'Camila Duarte',
    telefone: '5511993458899',
    email: 'camila.duarte@gmail.com',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    origem: 'whatsapp',
    objetivo_interesse: 'Definição muscular e hipertrofia com consultoria VIP',
    status: 'proposta_enviada',
    temperatura: 'quente',
    desafio_ativo_id: 'des-lead-02',
    desafio_ativo_titulo: 'Desafio 10 Minutos Metabólicos Sem Peso',
    data_envio_desafio: '2026-09-17T11:00:00Z',
    dias_desafio_decorridos: 4,
    etapa_followup: 4,
    data_criacao: '2026-09-15T09:30:00Z',
    ultimo_contato: '2026-09-20T17:45:00Z',
    proximo_followup: 'Hoje',
    valor_estimado_plano: 520,
    notas: 'Fez o desafio metabólico e adorou a energia. Proposta VIP 3x/semana enviada.',
    historico_interacoes: [
      {
        id: 'int-04',
        data: '2026-09-20T17:45:00Z',
        dataFormatada: 'Ontem às 17:45',
        tipo: 'proposta_apresentada',
        titulo: 'Proposta Comercial VIP Apresentada',
        descricao: 'Apresentou proposta do plano Presencial VIP 3x/semana (R$ 520/mês).',
      },
      {
        id: 'int-05',
        data: '2026-09-18T16:00:00Z',
        dataFormatada: '18/09/2026 às 16:00',
        tipo: 'followup_realizado',
        titulo: 'Ponte de Conversão',
        descricao: 'Elogiou a adesão ao desafio de 10 min e abriu conversa sobre planos.',
      },
      {
        id: 'int-06',
        data: '2026-09-17T11:00:00Z',
        dataFormatada: '17/09/2026 às 11:00',
        tipo: 'desafio_enviado',
        titulo: 'Desafio Metabólico Enviado',
        descricao: 'Disparo do desafio inicial pelo WhatsApp.',
      },
    ],
  },
  {
    id: 'lead-04',
    profissional_id: 'prof-001',
    nome: 'Felipe Nogueira',
    telefone: '5511981223344',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    origem: 'instagram',
    objetivo_interesse: 'Voltar a treinar após 2 anos sedentário',
    status: 'novo',
    temperatura: 'morno',
    etapa_followup: 0,
    data_criacao: '2026-09-21T09:10:00Z',
    ultimo_contato: '2026-09-21T09:10:00Z',
    proximo_followup: 'Hoje',
    valor_estimado_plano: 350,
    notas: 'Comentou no post "Como voltar a treinar sem lesão". Pronto para receber o 1º desafio.',
    historico_interacoes: [
      {
        id: 'int-07',
        data: '2026-09-21T09:10:00Z',
        dataFormatada: 'Hoje às 09:10',
        tipo: 'mensagem_whatsapp',
        titulo: 'Lead Capturado no Instagram',
        descricao: 'Enviou mensagem no direct demonstrando interesse em retomar.',
      },
    ],
  },
  {
    id: 'lead-05',
    profissional_id: 'prof-001',
    nome: 'Juliana Prado',
    telefone: '5511997788990',
    email: 'juliana.prado@advocacia.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    origem: 'presencial_academia',
    objetivo_interesse: 'Emagrecimento rápido e preparação para corrida',
    status: 'convertido',
    temperatura: 'quente',
    desafio_ativo_id: 'des-lead-04',
    desafio_ativo_titulo: 'Desafio Hidratação Matinal + 6.000 Passos',
    data_envio_desafio: '2026-09-12T08:00:00Z',
    dias_desafio_decorridos: 9,
    etapa_followup: 4,
    data_criacao: '2026-09-10T15:00:00Z',
    ultimo_contato: '2026-09-16T19:00:00Z',
    valor_estimado_plano: 480,
    notas: 'Converteu com sucesso! Fechou plano Presencial 3x/semana.',
    historico_interacoes: [
      {
        id: 'int-08',
        data: '2026-09-16T19:00:00Z',
        dataFormatada: '16/09/2026 às 19:00',
        tipo: 'convertido_aluno',
        titulo: '🎉 Convertido em Aluno!',
        descricao: 'Assinou contrato de 6 meses da consultoria presencial.',
      },
    ],
  },
  {
    id: 'lead-06',
    profissional_id: 'prof-001',
    nome: 'Thiago Martins',
    telefone: '5511965432109',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    origem: 'trafego_pago',
    objetivo_interesse: 'Ganho de massa muscular magra',
    status: 'em_followup',
    temperatura: 'frio',
    desafio_ativo_id: 'des-lead-01',
    desafio_ativo_titulo: 'Desafio 3 Dias Sem Açúcar Líquido & Refri',
    data_envio_desafio: '2026-09-14T15:00:00Z',
    dias_desafio_decorridos: 7,
    etapa_followup: 5,
    data_criacao: '2026-09-13T12:00:00Z',
    ultimo_contato: '2026-09-15T10:00:00Z',
    proximo_followup: 'Hoje',
    valor_estimado_plano: 320,
    notas: 'Parou de responder há 5 dias. Candidato ideal para mensagem de reativação.',
    historico_interacoes: [
      {
        id: 'int-09',
        data: '2026-09-14T15:00:00Z',
        dataFormatada: '14/09/2026 às 15:00',
        tipo: 'desafio_enviado',
        titulo: 'Desafio Enviado',
        descricao: 'Recebeu o desafio mas visualizou e não respondeu o check-in.',
      },
    ],
  },
];


