import { DesafioTemplate } from '../../types';

/**
 * Biblioteca Nativa de Desafios - RadarMove
 * Templates globais do sistema (profissional_id: null)
 */
export const DESAFIOS_NATIVOS_RADARMOVE: Omit<DesafioTemplate, 'id'>[] = [
  // =========================================================================
  // CATEGORIA: Lazer Ativo
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Lazer Ativo',
    titulo: 'Oxigenar a mente (Sexta-feira)',
    mensagem_whatsapp: 'Sextou! O asfalto já deu o que tinha que dar. O desafio RadarMove deste fim de semana é oxigenar a mente. Escolha uma rota nova: uma trilha, uma caminhada na areia ou um parque que você não visita faz tempo. Vá curtir e me mande uma foto do visual!',
    tempo_estimado: 'Fim de semana',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lazer Ativo',
    titulo: 'Esporte em Grupo',
    mensagem_whatsapp: 'Treinar não precisa ser solitário. O desafio de hoje é o movimento em grupo! Chame os amigos para uma partida de vôlei de praia, altinha ou um esporte ao ar livre. O importante é suar, se divertir e desestressar. Bom jogo!',
    tempo_estimado: '1h',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Lazer Ativo',
    titulo: 'Vento no rosto (Bike)',
    mensagem_whatsapp: "Que tal trocar quatro rodas por duas hoje? O desafio é alugar uma bike ou pegar a sua e pedalar ao ar livre. Sinta o vento, mude a rota e faça do seu exercício um momento de lazer. Manda um 'Feito 💪' quando terminar a rota.",
    tempo_estimado: '30-45 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lazer Ativo',
    titulo: 'Equilíbrio e Recuperação',
    mensagem_whatsapp: 'O descanso faz parte do treino. Seu desafio para este fim de semana é o equilíbrio: faça uma caminhada leve de 30 minutos ao ar livre e, à noite, relaxe com uma boa taça de vinho tinto. Recarregue as energias, segunda-feira tem mais!',
    tempo_estimado: '30 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lazer Ativo',
    titulo: 'Exploração de fim de semana',
    mensagem_whatsapp: 'Vai pegar a moto ou o carro no fim de semana? Aproveite a viagem para explorar! Estacione, encontre um mirante ou uma ladeira nova e faça uma caminhada exploratória. O corpo foi feito para se mover em todos os terrenos. Aproveite!',
    tempo_estimado: '20 min',
    dificuldade: 'Fácil',
  },

  // =========================================================================
  // CATEGORIA: Mindset Estoico (5 nativos iniciais + 4 complementares)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Foco no que você controla',
    mensagem_whatsapp: 'Começando mais uma semana! Lembre-se do princípio estoico: não controlamos o trânsito, as urgências do trabalho ou o clima. Mas controlamos o que colocamos no prato e a energia que deixamos no treino. Foco no que está nas suas mãos hoje!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'O obstáculo é o caminho',
    mensagem_whatsapp: 'Imprevistos acontecem. Faltou tempo para o treino completo hoje? Não tem problema, o obstáculo é o caminho. Adapte. O desafio de hoje é fazer 15 minutos de exercícios com o peso do corpo na sala de casa. Feito é melhor que perfeito. Me avise quando terminar!',
    tempo_estimado: '15 min',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Disciplina supera motivação',
    mensagem_whatsapp: 'A motivação te faz começar, mas é o hábito que te faz continuar. Hoje pode ser um daqueles dias em que a vontade é zero. É exatamente hoje que o treino vale o dobro para a sua disciplina. Deixe a roupa separada. Te espero mais tarde!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Desafiador',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'O poder do agora',
    mensagem_whatsapp: 'Não sofra pelo treino que você perdeu ontem, nem pela dieta que vai furar amanhã. A filosofia nos ensina a viver o agora. O que você pode fazer pela sua saúde NESTE momento? Beba um copão de água agora e garanta o treino de hoje.',
    tempo_estimado: 'Imediato',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Micro-vitórias diárias',
    mensagem_whatsapp: 'Grandes resultados são apenas a soma de pequenas vitórias diárias. O desafio RadarMove de hoje é simples, mas poderoso: durma 30 minutos mais cedo e bata sua meta de água. O corpo se constrói no descanso. Vamos juntos!',
    tempo_estimado: 'Diário',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Amor Fati: Abrace o Desconforto',
    mensagem_whatsapp: 'A filosofia estoica ensina o Amor Fati — amar o destino, mesmo quando o treino é duro e o cansaço aperta. Não reclame do esforço; agradeça pelo fato de você ter um corpo forte e saudável capaz de se mover. Encare o treino de hoje com gratidão!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Memento Mori: O Valor do Seu Tempo',
    mensagem_whatsapp: 'Lembre-se de que o tempo é o único recurso que você não pode recuperar. Cuidar da sua saúde hoje não é vaidade, é respeito pelo tempo de vida que você tem pela frente. Priorize o que realmente importa: treino pago hoje!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'Praemeditatio Malorum: Antecipando os Obstáculos',
    mensagem_whatsapp: 'Antes do dia começar, antecipe as tentações e preguiça: Hoje vão me oferecer doces e o dia será corrido. Ao prever as dificuldades mentalmente, você não é pego de surpresa e toma as melhores decisões. Esteja um passo à frente!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Mindset Estoico',
    titulo: 'O Elogio ao Esforço Silencioso (Marco Aurélio)',
    mensagem_whatsapp: 'Não perca tempo discutindo sobre o que um homem bom deve ser. Seja um. Não precisa postar nem anunciar: apenas vá lá, execute sua rotina e vença o dia em silêncio. A consistência fala mais alto que qualquer palavra!',
    tempo_estimado: 'Leitura 30s',
    dificuldade: 'Fácil',
  },

  // =========================================================================
  // CATEGORIA: Lifestyle 23h (2 iniciais + 12 novos = 14)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Despertar Hídrico Sem Celular',
    mensagem_whatsapp: "Bom dia! Seu desafio matinal das 23h fora da academia: antes de checar mensagens ou redes sociais, beba 500ml de água em temperatura ambiente e tome 5 minutos de luz solar natural na janela ou varanda. Mande um 'Feito ☀️' quando cumprir!",
    tempo_estimado: '5 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Meta 8.000 Passos no Asfalto',
    mensagem_whatsapp: 'Hoje o foco é não passar o dia sentado. Seu desafio RadarMove é atingir no mínimo 8.000 passos até o fim da noite. Vale descer um ponto antes, usar escadas ou fazer uma caminhada leve após o almoço. Mostre o print do contador no final do dia!',
    tempo_estimado: 'Ao longo do dia',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Luz Solar Matinal Direta (10 min)',
    mensagem_whatsapp: "Seu relógio biológico agradece! Antes das 10h da manhã, vá para a janela ou ar livre e receba 10 minutos de luz solar natural nos olhos (sem óculos escuros). Isso regula a melatonina para esta noite e dispara a energia matinal. Mande um '☀️ Feito'!",
    tempo_estimado: '10 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Escadas em Vez do Elevador',
    mensagem_whatsapp: 'Desafio anti-sedentarismo corporativo: hoje você está terminantemente proibido de usar elevadores ou escadas rolantes para trajetos de até 3 andares. Suba no ritmo constante. Cada degrau é gasto calórico invisível somado ao seu plano!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Pausa Ativa a Cada 90 Minutos',
    mensagem_whatsapp: 'Ficar sentado por mais de 90 minutos contínuos reduz sua sensibilidade à insulina. Hoje, coloque um alarme: a cada 1h30 de trabalho, levante, beba 200ml de água e dê uma volta de 2 minutos. Vamos destravar essa postura!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Almoço Longe da Mesa de Trabalho',
    mensagem_whatsapp: 'Comer olhando para a tela do computador ou rolando o feed sabota a saciedade. Seu desafio de 23h hoje: faça sua refeição principal sentado longe de telas e computador. Mastigue com calma por pelo menos 15 minutos. Topa o compromisso?',
    tempo_estimado: '15-20 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Estacionar a 500m do Destino',
    mensagem_whatsapp: 'Hack de gasto calórico não planejado (NEAT): ao ir trabalhar, ao mercado ou a um compromisso, estacione o carro propositalmente a 5 quadras de distância ou desça um ponto antes. Movimento integrado à sua rotina real!',
    tempo_estimado: '5-8 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Desconexão Noturna das 21h',
    mensagem_whatsapp: 'Seu descanso é sagrado para sua recuperação muscular. Desafio de hoje: a partir das 21h30, silencie notificações de trabalho e coloque o celular em modo Não Perturbe. Uma mente calma produz noites de sono que realmente queimam gordura.',
    tempo_estimado: 'Noturno',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Banho Térmico Energizante',
    mensagem_whatsapp: 'Final de banho revigorante: nos últimos 45 segundos do seu banho hoje, vire a torneira para água fria e controle sua respiração pelo nariz. Estimula o sistema imune, alerta mental e gasto energético. Me conta como foi a sensação!',
    tempo_estimado: '1 min',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Check-in de Postura na Condução/Trânsito',
    mensagem_whatsapp: 'Preso no trânsito ou no transporte? Ajuste seu encosto: afaste os ombros das orelhas, ative o abdômen puxando o umbigo levemente para dentro e apoie a lombar. Menos dor nas costas no fim do dia!',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Caminhada Digestiva Pós-Refeição (10 min)',
    mensagem_whatsapp: 'Dica de ouro para diminuir o pico glicêmico pós-almoço: em vez de deitar ou sentar no sofá, faça 10 minutos de caminhada leve em ritmo de passeio. Melhora a digestão e combate a famosa moleza da tarde!',
    tempo_estimado: '10 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Garrafa de 1.5L no Campo de Visão',
    mensagem_whatsapp: 'Não confie na sede, confie no visual! Encha uma garrafa de pelo menos 1.5L e deixe-a do lado do seu teclado de trabalho o dia todo. O desafio é secar a primeira garrafa até as 14h e encher a segunda. Mande a foto da garrafa cheia!',
    tempo_estimado: 'Dia todo',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Alongamento Axial Matinal na Cama',
    mensagem_whatsapp: 'Assim que abrir os olhos antes de pisar no chão: estique todo o corpo como se quisesse encostar a ponta dos dedos dos pés na cabeceira e as mãos no teto. Puxe ar fundo por 3 vezes e ative a circulação. Bom dia com energia!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Lifestyle 23h',
    titulo: 'Auditoria de Horas de Tela Semanal',
    mensagem_whatsapp: 'Momento honestidade com a sua saúde: abra agora as configurações do celular e veja o seu Tempo de Uso diário. Se você tem 3 horas para redes sociais, você tem 45 minutos para seu treino e saúde. Olhe com carinho e faça um compromisso com você!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },

  // =========================================================================
  // CATEGORIA: Desafio de Bolso (2 iniciais + 12 novos = 14)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Reset de 3 Minutos na Cadeira',
    mensagem_whatsapp: 'Trabalhando direto sem pausa? Pare agora por 3 minutos: faça 10 rotações de ombros, 10 extensões torácicas apoiado na cadeira e 1 minuto de cócoras para destravar o quadril e a lombar. O corpo agradece e o foco volta dobrado!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Mini-HIIT Anti-Cancelamento (12 Min)',
    mensagem_whatsapp: 'Sem tempo para vir ao treino hoje? O treino não está perdido! Faça este circuito em casa: 4 rounds de 30s de polichinelos, 30s de agachamento livre, 30s de prancha isométrica e 30s de descanso. 12 minutos e está pago. Me avise quando terminar!',
    tempo_estimado: '12 min',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Prancha Isométrica de 60 Segundos',
    mensagem_whatsapp: "Desafio de bolso express: 1 minuto no chão, antebraços apoiados, glúteos travados e abdômen de pedra. Sem desculpas de tempo. Mande 'Feito 🔥' quando bater os 60 segundos!",
    tempo_estimado: '1 min',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Tabata Relâmpago de Polichinelo (4 Min)',
    mensagem_whatsapp: 'Em apenas 4 minutos você acorda seu metabolismo: 20 segundos de polichinelos na intensidade máxima, 10 segundos de descanso, repetindo por 8 rounds. Coloque a música favorita e faça agora na sala ou quarto!',
    tempo_estimado: '4 min',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Agachamento Isométrico na Parede (Wall Sit 90s)',
    mensagem_whatsapp: 'Desafio de resistência muscular pura: encoste as costas na parede, desça até as coxas ficarem paralelas ao chão (90 graus) e segure por 90 segundos sem apoiar as mãos nas pernas. As coxas vão tremer! Consegue completar?',
    tempo_estimado: '90s',
    dificuldade: 'Desafiador',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Desafio 50 Flexões Fracionadas no Dia',
    mensagem_whatsapp: 'Desafio cumulativo de força: hoje você precisa somar 50 flexões de braço ao longo do seu dia. Pode fazer 5 séries de 10 ao lado da mesa de trabalho, no quarto ou na cozinha. Vale fazer com joelhos no chão. Avise quando bater a meta!',
    tempo_estimado: 'Ao longo do dia',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Mobilidade Torácica do Gato e Vaca',
    mensagem_whatsapp: 'Sentindo a coluna rígida? Fique em 4 apoios por 2 minutos e faça 15 repetições lentas da transição Gato-Vaca (arredondando e estendendo a coluna sincronizado com a respiração). Alívio imediato para a coluna lombar e torácica.',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Passadas Afundo no Corredor (30 passos)',
    mensagem_whatsapp: 'Precisa ir até a cozinha ou trocar de cômodo? Vá fazendo passadas em afundo! São 15 passos para cada perna com joelho quase tocando o chão e tronco ereto. Ativação de quadríceps e glúteos instantânea!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Mobilidade de Tornozelo na Parede',
    mensagem_whatsapp: 'Tornozelo travado sabota seu agachamento e sobrecarrega o joelho. Faça agora: pé a 10cm da parede, empurre o joelho para frente sem tirar o calcanhar do chão por 15 repetições cada perna. 2 minutos que salvam seu treino!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Respiração Box (4x4 Anti-Estresse)',
    mensagem_whatsapp: 'Coração acelerado ou cabeça a mil? Faça a Respiração Quadrada: inspire em 4 segundos, segure o ar por 4s, expire em 4s e segure sem ar por 4s. Repita por 3 minutos. O sistema nervoso central acalma imediatamente.',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Desafio 100 Agachamentos Livres',
    mensagem_whatsapp: 'Vamos aquecer as pernas e elevar o gasto calórico? Faça 4 blocos de 25 agachamentos ao longo da manhã. Fez uma ligação de negócios? Agache 25 vezes. Respondeu emails importantes? Mais 25. Bora acumular esse volume!',
    tempo_estimado: 'Ao longo do dia',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Descompressão de Punhos e Antebraços',
    mensagem_whatsapp: 'Digitou o dia todo? Estenda o braço à frente e puxe os dedos para trás por 30s. Depois inverta para baixo. 1 minuto para cada mão para prevenir tendinites e dores no antebraço. Faça agora!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Panturrilhas no Degrau (3x20 repetições)',
    mensagem_whatsapp: 'A panturrilha é o segundo coração do corpo humano e bombeia o sangue de volta para cima. Vá até um degrau ou batente: suba na ponta dos pés no máximo da contração e desça alongando bem. 3 séries de 20 repetições. Queima garantida!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Bolso',
    titulo: 'Prancha Lateral com Elevação de Perna',
    mensagem_whatsapp: 'Fortalecimento de oblíquos e glúteo médio: prancha lateral no antebraço por 30 segundos de cada lado. Se quiser subir o nível, eleve a perna de cima por 5 vezes. Estabilidade máxima para proteger seu quadril!',
    tempo_estimado: '2 min',
    dificuldade: 'Médio',
  },

  // =========================================================================
  // CATEGORIA: Conversão & Leads (2 iniciais + 12 novos = 14)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Desafio Detox Postural (Dia 1)',
    mensagem_whatsapp: 'Olá! Preparado para começar seu Desafio Postural de 3 Dias? Seu compromisso hoje leva apenas 2 minutos: faça o alinhamento escapular na parede que gravei no vídeo curto abaixo. Faça agora e me diga se sentiu a tensão aliviar na parte alta das costas!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Teste de Mobilidade de Quadril',
    mensagem_whatsapp: "Tudo bem? Como prometido, aqui está seu mini-teste de mobilidade. Faça o teste de agachamento profundo segurando no batente da porta e repare se seu calcanhar levanta do chão. Me responde aqui com 'Levantou' ou 'Ficou no chão' para eu avaliar seu padrão!",
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: 3 Dicas de Ouro Para Secar a Barriga',
    mensagem_whatsapp: 'Tudo bem? Preparei um checklist rápido e sem enrolação com 3 ajustes alimentares que meus alunos aplicam para desinchar em 7 dias sem passar fome. Posso te enviar o áudio explicativo de 2 minutinhos por aqui?',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Avaliação Visual de Postura',
    mensagem_whatsapp: 'Olá! Você sente incômodo no pescoço ou lombar depois do trabalho? Se quiser, tire uma foto de lado (perfil) encostado em uma parede e me envie aqui. Faço uma triagem postural rápida e te digo exatamente o que fortalecer!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Desafio 24h: O Teste do Café Sem Açúcar',
    mensagem_whatsapp: 'Que tal um desafio de 1 dia para reprogramar seu paladar? Tome seu café de amanhã 100% puro, sem adoçante e sem açúcar por apenas 24h. Parece simples, mas destrava sua sensibilidade à insulina. Aceita o convite?',
    tempo_estimado: '24h',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Treino Express de 15 Minutos em PDF',
    mensagem_whatsapp: 'Muitos me dizem que não têm 1 hora para academia. Por isso montei um treino de 15 minutos de peso do corpo que você pode fazer no tapete da sala para queimar calorias. Quer que eu te envie o PDF de presente?',
    tempo_estimado: '15 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Calculadora de Proteína Personalizada',
    mensagem_whatsapp: 'Oi! A maioria das pessoas come metade da proteína que precisa e por isso sente fome toda hora. Me fala seu peso atual e qual seu objetivo principal (secar ou ganhar massa) que eu calculo a sua meta diária exata agora!',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Desafio de 3 Dias: Sem Refri, Mais Disposição',
    mensagem_whatsapp: 'Convite especial para os próximos 3 dias: zero refrigerante ou sucos açucarados. Troque por água com limão ou gás. Se topar, vou te mandar um lembrete diário para mantermos o foco juntos. Vamos começar hoje?',
    tempo_estimado: '3 dias',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Vídeo de Alívio de Dor Ciática',
    mensagem_whatsapp: 'Você já sentiu aquela fisgada chata no glúteo ou descendo pela perna? Gravei um alongamento de 40 segundos que destravou as costas de 5 alunos esta semana. Quer ver o vídeo para testar aí no seu sofá?',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Quiz de Perfil Metabólico & Rotina',
    mensagem_whatsapp: "Olá! Para eu entender melhor seu momento: qual dessas 3 frases mais te descreve hoje? 1) 'Treino mas não vejo resultado', 2) 'Falta de tempo total', ou 3) 'Cansaço constante e dores'. Me responde só com o número!",
    tempo_estimado: '30s',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Desafio Convite: 1 Treino Experimental no App',
    mensagem_whatsapp: 'Que tal testar como funciona uma consultoria personalizada de verdade? Liberei um acesso de teste de 7 dias com uma rotina montada para sua meta. Sem compromisso. Posso gerar seu link de acesso?',
    tempo_estimado: '7 dias',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Check-in de Fim de Semana: Estratégia sem Culpa',
    mensagem_whatsapp: 'Fim de semana chegando! A maioria joga fora o resultado da semana inteira entre sexta e domingo. Quer que eu te mande 2 regras práticas para beber socialmente e comer fora sem ganhar gordura?',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Degustação: Áudio de 60s sobre Creatina e Mitos',
    mensagem_whatsapp: 'Você toma ou já pensou em tomar Creatina? Muita gente ainda acha que retém líquido ruim ou engorda, mas a ciência prova o oposto. Gravei um áudio de 1 minuto desmistificando. Posso te mandar aqui?',
    tempo_estimado: '1 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Desafio de Conversão',
    titulo: 'Desafio Retenção: O Retorno Triunfante',
    mensagem_whatsapp: 'Faz alguns dias que você não aparece nos treinos e seu corpo sente a falta do ritmo! Não precisa recomeçar do zero nem fazer um treino pesado. Que tal fazer apenas 20 minutos hoje só para manter a chama acesa? Te espero!',
    tempo_estimado: '20 min',
    dificuldade: 'Médio',
  },

  // =========================================================================
  // CATEGORIA: Nutrição & Hidratação (2 iniciais + 12 novos = 14)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Proteína no Primeiro Prato',
    mensagem_whatsapp: 'Meta nutricional simples para hoje: garanta que sua primeira refeição do dia contenha uma porção sólida de proteína (ovos, iogurte desnatado, frango ou whey). Nada de começar o dia apenas com carboidratos simples. Mande a foto do prato!',
    tempo_estimado: 'Primeira refeição',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Zero Açúcar Líquido por 24h',
    mensagem_whatsapp: 'Desafio de corte estratégico: nas próximas 24 horas, você está proibido de consumir açúcar líquido (refrigerantes comuns, sucos de caixinha, café com açúcar refinado ou energéticos doces). Troque por água, café preto ou chá sem açúcar. Topa o teste?',
    tempo_estimado: '24h',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Regra das Cores no Prato (Mínimo 3 Cores)',
    mensagem_whatsapp: 'Comida de verdade tem cor natural! Seu desafio no almoço ou jantar de hoje é montar um prato com no mínimo 3 cores vivas de vegetais e legumes diferentes (ex: brócolis, cenoura, tomate). Prato colorido é micronutriente direto na veia!',
    tempo_estimado: 'Almoço',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Meta 35ml de Água por Quilo',
    mensagem_whatsapp: 'Hidratação calculada para performance: multiplique seu peso corporal por 35ml. Essa é sua meta obrigatória de água para hoje! Divida em copos de 300ml ao longo do dia e não deixe tudo para a noite. Vamos bater a meta?',
    tempo_estimado: 'Diário',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Substituição Consciente no Lanche da Tarde',
    mensagem_whatsapp: 'O perigo mora na fome das 16h! Hoje, troque o salgadinho, pão de queijo ou biscoito por uma opção inteligente: fruta com pasta de amendoim ou um pote de iogurte com aveia. Mande a foto do seu lanche proteico!',
    tempo_estimado: 'Tarde',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Sem Fritura por 48 Horas',
    mensagem_whatsapp: 'Desafio anti-inflamatório: pelas próximas 48 horas, retire qualquer preparação frita do cardápio (pastel, batata frita, empanados). Prefira grelhados, cozidos, assados ou na airfryer. O estômago fica leve e o treino rende mais!',
    tempo_estimado: '48h',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'O Sal Verde: Redução de Sódio Embutido',
    mensagem_whatsapp: 'Hoje o foco é reduzir alimentos ultraprocessados ricos em sódio escondido (molhos prontos, temperos em cubo, embutidos). Tempere seus pratos com alho, cebola, cúrcuma, orégano e limão. Paladar apurado e menos retenção!',
    tempo_estimado: 'Diário',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Shot Matinal Digestivo com Limão',
    mensagem_whatsapp: 'Ao acordar, esprema 1/2 limão em 150ml de água morna com uma pitada de cúrcuma ou gengibre em pó. Ajuda na produção de enzimas digestivas e prepara seu trato intestinal para o dia. Experimente e sinta a diferença!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Jantar Leve: Carboidrato Inteligente',
    mensagem_whatsapp: 'Hoje no jantar, priorize carboidratos de digestão limpa e ricos em fibras (abóbora, batata doce ou raízes) acompanhados de uma proteína magra. Evite pizzas ou massas pesadas antes de dormir para não prejudicar seu sono profundo!',
    tempo_estimado: 'Noite',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Regra dos 5 Ingredientes no Rótulo',
    mensagem_whatsapp: 'Desafio do rótulo limpo: hoje você só come o que a natureza dá ou produtos que tenham no máximo 5 ingredientes na lista do rótulo (sem nomes químicos estranhos). Descasque mais e desembale menos!',
    tempo_estimado: 'Diário',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Foto do Carrinho Saudável no Mercado',
    mensagem_whatsapp: 'A dieta começa no supermercado! Se você não comprar besteiras, você não vai comê-las em casa quando bater a ansiedade. No próximo mercado, encha a base do carrinho com hortifruti e proteínas e me mande uma foto do carrinho campeão!',
    tempo_estimado: 'Compras',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'A Regra dos 20 Minutos de Mastigação',
    mensagem_whatsapp: 'Seu cérebro leva cerca de 15 a 20 minutos para emitir o sinal de saciedade (leptina). No almoço de hoje, pouse o garfo na mesa entre uma garfada e outra e mastigue bem cada pedaço. Você vai comer menos e se sentir muito mais leve!',
    tempo_estimado: 'Refeição',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Meta das 2 Frutas Inteiras no Dia',
    mensagem_whatsapp: 'Nada de suco coado onde as fibras vão para o lixo. Seu desafio hoje é consumir 2 porções de frutas inteiras com casca ou bagaço (ex: maçã, pera, laranja com bagaço ou kiwi). Intestino funcionando como um relógio!',
    tempo_estimado: 'Diário',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Nutrição',
    titulo: 'Água com Gás e Limão em Saídas',
    mensagem_whatsapp: 'Vai sair para jantar ou encontrar amigos hoje? O truque dos mestres da definição: intercale cada copo de bebida ou drink com um copo grande de água com gás, gelo e rodelas de limão. Zero ressaca, menos calorias e hidratação nota 10!',
    tempo_estimado: 'Noite',
    dificuldade: 'Fácil',
  },

  // =========================================================================
  // CATEGORIA: Recuperação & Sono (2 iniciais + 12 novos = 14)
  // =========================================================================
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Higiene de Sono & Tela Azul Off',
    mensagem_whatsapp: 'O músculo cresce e a gordura é queimada no descanso profundo. Desafio desta noite: desligue telas (celular, TV e notebook) 45 minutos antes de deitar e mantenha o quarto completamente escuro e fresco. Uma noite de sono impecável para amanhã render mais!',
    tempo_estimado: '45 min antes de dormir',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Descompressão Lombar Noturna',
    mensagem_whatsapp: 'Antes de deitar, dedique 4 minutos para a sua coluna: abrace os dois joelhos deitado de costas por 1 minuto, faça 1 minuto de postura da criança (alongamento de glúteos e dorsais) e finalize com respiração diafragmática lenta. Deite e descanse!',
    tempo_estimado: '4 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Regra 10-3-2-1 para Sono Profundo',
    mensagem_whatsapp: 'Método comprovado para dormir rápido: 10h antes de deitar: nada de cafeína; 3h antes: nada de refeições pesadas; 2h antes: pare de trabalhar; 1h antes: zero telas. Aplique esta fórmula hoje e acorde outra pessoa amanhã!',
    tempo_estimado: 'Noturno',
    dificuldade: 'Médio',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Quarto 100% Escuro (Caverna do Sono)',
    mensagem_whatsapp: 'Qualquer luzinha de LED ou fresta de cortina diminui a produção de melatonina durante a noite. Desafio de hoje: cubra os LEDs do quarto e feche as cortinas completamente. Durma no escuro absoluto e note a profundidade do seu sono!',
    tempo_estimado: 'Noturno',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Auto-Liberação Miofascial com Bolinha',
    mensagem_whatsapp: 'Alívio de tensão miofascial em casa: pegue uma bolinha de tênis ou similar, posicione entre as escápulas ou no glúteo encostado na parede e faça movimentos circulares lentos nos pontos de dor. 3 minutos que soltam o músculo travado!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Banho Morno 60 Minutos Antes de Deitar',
    mensagem_whatsapp: 'A ciência do sono mostra que um banho morno 1 hora antes de dormir dilata os vasos e depois reduz a temperatura corporal central, sinalizando ao cérebro que é hora de adormecer. Tome seu banho morno com calma hoje e vá relaxar!',
    tempo_estimado: '10 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Pernas Elevadas na Parede por 5 Minutos',
    mensagem_whatsapp: 'Drenagem natural e alívio de pernas cansadas: deite no chão, encoste o quadril na parede e coloque as duas pernas estendidas para cima formando 90 graus. Fique assim por 5 minutos respirando fundo. O retorno venoso alivia o inchaço imediatamente!',
    tempo_estimado: '5 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Leitura Física em Vez de Celular na Cama',
    mensagem_whatsapp: 'Troque o feed infinito de redes sociais por 10 páginas de um livro físico antes de apagar as luzes. Ler acalma as ondas cerebrais e induz ao sono natural em minutos, sem a estimulação tóxica da dopamina rápida. Topa a troca?',
    tempo_estimado: '15 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Descompressão de Cervical e Trapézio',
    mensagem_whatsapp: 'Tensão acumulada no pescoço pelo uso do computador? Puxe a cabeça suavemente para o lado direito por 40 segundos e depois para o lado esquerdo. Em seguida, queixo no peito. Respire aliviando todo o peso do dia!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Chá Relaxante Noturno',
    mensagem_whatsapp: 'Ritual noturno calmante: prepare uma xícara generosa de chá de camomila, melissa ou mulungu 45 minutos antes de dormir. O calor da xícara e os fitoterápicos naturais preparam seu corpo para o descanso anabólico!',
    tempo_estimado: '5 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Alongamento Suave de Glúteos em 4',
    mensagem_whatsapp: 'Deitado de costas, cruze o tornozelo direito sobre o joelho esquerdo formando um número 4 e puxe a coxa esquerda em direção ao peito por 60 segundos. Repita do outro lado. Adeus dor lombar e tensão do quadril!',
    tempo_estimado: '2 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Ventilação e Quarto Fresco (19°C a 21°C)',
    mensagem_whatsapp: 'O corpo precisa esfriar para entrar no estágio de sono profundo (REM e ondas lentas). Deixe o quarto fresco e bem arejado antes de deitar. Evite cobertores excessivos que causem suor noturno. Sono fresco = sono reparador!',
    tempo_estimado: 'Noturno',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Esvaziamento Mental no Papel (Brain Dump)',
    mensagem_whatsapp: 'Não vá para a cama com a lista de pendências de amanhã girando na sua cabeça. Pegue um papel e anote tudo o que precisa fazer amanhã. Tirar da mente e colocar no papel reduz a ansiedade noturna em até 80%. Experimente hoje!',
    tempo_estimado: '3 min',
    dificuldade: 'Fácil',
  },
  {
    profissional_id: null,
    categoria: 'Recuperação',
    titulo: 'Descanso Ativo no Dia Off (Caminhada Zen)',
    mensagem_whatsapp: 'Hoje é dia de descanso dos treinos de força, mas descanso não significa imobilidade! Faça uma caminhada leve de 20 minutos no parque ouvindo uma música tranquila ou podcast. Promove circulação e limpa o lactato residual dos músculos!',
    tempo_estimado: '20 min',
    dificuldade: 'Fácil',
  },
];

