version: '3.8'

services:
  radarmove:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radarmove_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
